
[deployment]
[[deployment.targets]]
name = "stopify.com/landing pages"
url = "s3://stopify-20210804071346562200000001.s3-website.eu-west-3.amazonaws.com"


baseURL: "http://stopify-20210804071346562200000001.s3-website.eu-west-3.amazonaws.com"
title: Stopify - Github s3
